### PR TITLE
Design Fixes + Additional Miscellaneous Functionality

### LINKED ISSUE #55: Design Fixes + Additional Miscellaneous Functionality
## Instructions
- Update the Donation Modal to conditionally display the option to schedule a route for the donation.
- Convert the `UserProfile` page into the `ProfileModal`.
- Add furniture count to backend routes.

### Assign Route
- In the `DonationModal`, show the dropdowns when the donation status is `approved`, `scheduling`, and `scheduled`. The dropdowns should be clickable when the donations are `approved` and disabled otherwise.
- Query the backend `routes` table to get all route information.
- Populate the date dropdown with all unique possible dates in ascending order.
- The dropdown to select a route should be disabled until a date has been selected.
- Once a date has been selected, filter the route information to display the names of all the routes on the selected date.
- Upon clicking `Schedule Pickup`, send a post request to update the donation's `route_id` with the selected route and `order` initialized with the next available number. More specifically, the number of donations scheduled for that route + 1.
### Profile Modal
- Match the design for the `ProfileModal`. The modal appears on clicking the Profile dropdown in the navigation bar. The modal closes by clicking the **X**, Cancel, or outside of the modal.
- All functionality of the `UserProfile` should still be working after being converted to a modal (viewing/editing information, changing password).
### Add Furniture Count to Backend Routes
- Add to any backend route that gets any furniture items

## Resources
- [Donation Modal](https://www.figma.com/file/3DOUy8M8f1aWmKbpC63XMC/PNP-Wireframes?node-id=1675%3A16494&t=Lgo9M2pcJKXuMu2Q-0)
- [Chakra Select](https://chakra-ui.com/docs/components/select)
- [Chakra Modal](https://chakra-ui.com/docs/components/modal)
- [UserProfile](https://github.com/ctc-uci/patriots-and-paws-frontend/blob/dev/src/pages/UserProfile/UserProfile.jsx) code
- [ProfileModal](https://www.figma.com/file/3DOUy8M8f1aWmKbpC63XMC/PNP-Wireframes?node-id=1268%3A10757&t=Lgo9M2pcJKXuMu2Q-0)
- [Backend issue](https://github.com/ctc-uci/patriots-and-paws-backend/issues/34)

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #55

### CODE REVIEW

File: src/components/EditAccountModal/EditAccountModal.jsx [hunk 1]
```diff
@@ -115,15 +115,18 @@ const EditAccountModal = ({
...
-      setUsers(prev => prev.map(user => (user.id === data.id ? { ...updatedUser, ...e } : user)));
-      if (data.role === 'admin') {
-        setAdminUsers(prev =>
-          prev.map(user => (user.id === data.id ? { ...updatedUser, ...e } : user)),
-        );
-      } else {
-        setDriverUsers(prev =>
-          prev.map(user => (user.id === data.id ? { ...updatedUser, ...e } : user)),
-        );
+      console.log(setUsers);
```
Comment (ctc-devops) [inline src/components/EditAccountModal/EditAccountModal.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by jrock-3 — DISMISSED** [review]
lgtm

**Review by jrock-3 — DISMISSED** [review]
