### PR TITLE
Sitewide: Toasts

### LINKED ISSUE #117: Sitewide: Toasts
# Description
- Ensure only one toast is shown at all times. The newer toasts should replace any existing toasts.
- Ensure all existing toasts match the design in position and color. Create any missing toasts where possible.
- All toasts from a table should be at the bottom. All toasts from a modal action should be at the top of the page. This is a general reference, but double check with design with color as well.

# How to Recreate 
- Find any component with validation that puts errors in a toast.
- Recreate that error state and keep clicking.
- Example: try logging into the donor dashboard with the wrong credentials multiple times.

# Images
- Toasts in donor dashboard
image

# Files to look in

- wherever toasts are used (ex: donation modal with emailing, manage staff, manage donation form

# Resources
- [Closing Toasts Chakra](https://chakra-ui.com/docs/components/toast#closing-toasts)
- Use the User Flows in the Figma to help find all the toasts.

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #117

### CODE REVIEW

**Comment by tig-github** [comment]
have to check a few more things before requesting so going to unrequest

File: src/components/EditItemsList/EditItemsList.jsx [hunk 1]
```diff
@@ -56,11 +59,24 @@ const EditItemsList = ({ items, setItems, setNewEntries, setDeletedEntries, isAc
         shouldFocus: true,
       });
     } else {
-      setItems(prev => [...prev, { name: toCapitalCase(furnitureName), accepted: isAccepted }]);
+      setItems(prev => [...prev, { name: furnitureName, accepted: isAccepted }]);
       setNewEntries(prev => [
         ...prev,
         { name: toCapitalCase(furnitureName), accepted: isAccepted },
-      ]);
+      ]);      toast.closeAll();
```
Comment (ctc-devops) [inline src/components/EditItemsList/EditItemsList.jsx]: 🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `⏎`
```suggestion
      ]);
      toast.closeAll();
```

**Review by NwinNwin — DISMISSED** [review]
Very Nice!

**Review by jrock-3 — APPROVED** [review]
