### PR TITLE
Route Calendar and PDF: Fix Formatting

### LINKED ISSUE #124: Route Calendar and PDF: Fix Formatting
# Description
## Route Calendar
- Match the layout and design of the Today and arrow buttons as well as the cell background color of the current day. 
- Adjust the font sizes.
- Bottom portion of calendar is cut off
- Routes Calendar label appears to be missing
- Add padding to arrow buttons
- Increase size of Create Route button
- Ensure the calendar is not scrollable in all usages (ie: the calendar drawer and driver dashboard).
## Route PDF
- Add driver name to top section on the first page and remove it from all subsections.
- Add the Page count in the top right corner.
- Format furniture list to be bullet points with `##x [furniture name]` as the text.
- Format phone number to be `(xxx) xxx - xxxx`
- Adjust spacing and font size to match design.
- Instead of “Sunday, April 9, 2023,” replace the comma with a colon in between Sunday and April. 

# How to Recreate
- Open `RouteCalendar` and visually inspect the rendering of the components with your eyes

# Images
- N/A

# Files to look in
- RouteCalendar.jsx

# Resources
- [Route Calendar Figma](https://www.figma.com/file/3DOUy8M8f1aWmKbpC63XMC/PNP-Wireframes?node-id=3735-27150&t=NP6HG7Ejwj0RB5TV-4)
- [Route PDF Figma](https://www.figma.com/file/3DOUy8M8f1aWmKbpC63XMC/PNP-Wireframes?node-id=5243-50493&t=0Th6xBao39a8VlIY-4)
- [Fullcalendar Docs](https://fullcalendar.io/docs)

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #124

### CODE REVIEW

File: src/components/RoutePDF/RoutePDF.jsx [hunk 1]
```diff
@@ -38,8 +36,9 @@ const RoutePDF = ({ driverData, donationData, date }) => {
 
   useEffect(() => {
     const helper = async () => {
+      console.log(donationData);
```
Comment (ctc-devops) [inline src/components/RoutePDF/RoutePDF.jsx]: ⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

**Review by jrock-3 — DISMISSED** [review]
pending hang's comments

**Review by hang-m-cao — APPROVED** [review]
